name: forestinv_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter packages pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auth_buttons: ^2.0.4
  cached_network_image: ^3.1.0
  cloud_firestore: ^3.1.8
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  device_preview: ^1.0.0
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.1
  flutter_modular: ^3.3.1
  flutter_secure_storage: ^4.2.1
  font_awesome_flutter: ^9.1.0
  form_field_validator: ^1.1.0
  geolocator: ^8.2.0
  get: ^4.3.8
  get_it: ^7.2.0
  google_sign_in: ^5.2.3
  intl: ^0.17.0
  mask_text_input_formatter: ^2.1.0
  material_design_icons_flutter: ^5.0.6595
  material_floating_search_bar: ^0.3.6
  mobx: ^2.0.3
  photo_view: ^0.13.0
  rflutter_alert: ^2.0.4
  toggle_switch: ^1.4.0

dev_dependencies:
  build_runner: ^2.0.6
  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  mocktail: ^0.1.4

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 700
